### ISSUE TITLE
Application did not respond /tag

### ISSUE THREAD

**Issue by FelixArgyle** [Sven65/TagBot#13]
### 👟 Reproduction steps

/tag name:chop?

### 👍 Expected behavior

for it to output the tag.

### 👎 Actual Behavior

The application did not respond

### 🎲 Tagbot version

Rust rewrite

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

Likely just gonna be a common issue amongst slash commands since it does happen with drpg, tho usually works next usage with commands.

**Comment by Sven65** [comment]
Fixed :)
