### ISSUE TITLE
£help error

### ISSUE THREAD

**Issue by sudojunior** [Sven65/TagBot#3]
[Screenshot](https://owo.whats-th.is/f6ea88.png)
I don't know how this hasn't been reported already

**Comment by Sven65** [comment]
You forgot to add `http://` infront of your image URL, but I'm working on rewriting tagbot

**Comment by sudojunior** [comment]
@Sven65 it's owo so it has to be `https://` ¯\_(ツ)_/¯
alright then... *i'm still here if needed lol*

**Comment by Sven65** [comment]
Done
