### ISSUE TITLE
Time tag not showing locale's. 

### ISSUE THREAD

**Issue by ghost** [Sven65/TagBot#5]
The time tag `%H, %M, %S` not showing locale's.

**Comment by Sven65** [comment]
What do you mean?

**Comment by ghost** [comment]
the time showing is not locale's. Also it is not told in wiki it will shows locale's. 
I just thought why the date only shows locale's but time doesn't.

image: https://i.imgur.com/fTOsL5B.jpg
mine GMT +5:30Hrs

**Comment by Sven65** [comment]
That's because the time is based on the current time in JS, which is GMT+0

**Comment by Sven65** [comment]
A possible fix for this would be to allow for the time tags to have some sort of locale bit
